version: '3'
services:
  db:
    container_name: cf-notify
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
